[[OptimPack]]
arch = "aarch64"
git-tree-sha1 = "88701f1e2d134f822787f46beccf92f8dd6cc4d2"
os = "macos"

    [[OptimPack.download]]
    sha256 = "497c90f59d95b8ed9243bfcb83e5ac660de1434d41ee652499f43eeb28cce8c0"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.aarch64-apple-darwin.tar.gz"
[[OptimPack]]
arch = "aarch64"
git-tree-sha1 = "7f8548906c4d93c7377fc65f6ce7c4c0eee0eb70"
libc = "glibc"
os = "linux"

    [[OptimPack.download]]
    sha256 = "6d29b328e2c4393c284dc26253c936a8df549f6112324eca4eedb3d4e583740a"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.aarch64-linux-gnu.tar.gz"
[[OptimPack]]
arch = "aarch64"
git-tree-sha1 = "28c27d5377ac3befea36a737215631373e214171"
libc = "musl"
os = "linux"

    [[OptimPack.download]]
    sha256 = "eb31701e8e7a6a3cdb47d8995eb6eb10f891a3b43d552faa877dad45bba8f8a9"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.aarch64-linux-musl.tar.gz"
[[OptimPack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6267b5afb4aea1be5dc3495879983cf5300a8564"
libc = "glibc"
os = "linux"

    [[OptimPack.download]]
    sha256 = "9b358059dcdb24c1a1fa69bf621f704b02a791cec62152eb29bba3bf7910416f"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.armv6l-linux-gnueabihf.tar.gz"
[[OptimPack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "01e06bc41392a9a50f683d8721068370f00d892a"
libc = "musl"
os = "linux"

    [[OptimPack.download]]
    sha256 = "a659d8b64c764d7a3e1c5dc506893864d0d3b536bbb238215ab928c5a23c96f4"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.armv6l-linux-musleabihf.tar.gz"
[[OptimPack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "661b5d863ead367c96df88cf1c4b34236aa61749"
libc = "glibc"
os = "linux"

    [[OptimPack.download]]
    sha256 = "98e7375360a28673e2bef67c47bf9e518910259453f91e8720cf7eab78370f0d"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.armv7l-linux-gnueabihf.tar.gz"
[[OptimPack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "21db565a07ae0f4ce3b37fb91cd60bc5a9902785"
libc = "musl"
os = "linux"

    [[OptimPack.download]]
    sha256 = "3397777fcc6983f9581cd97619a945bef57ed3e83f910bd5ad517aed35de4eea"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.armv7l-linux-musleabihf.tar.gz"
[[OptimPack]]
arch = "i686"
git-tree-sha1 = "18f69c3b2612a33688186561fc03289ebb2561de"
libc = "glibc"
os = "linux"

    [[OptimPack.download]]
    sha256 = "9b255cb7475c33636903de928f6d11c719883340f1270d54cc22340da9db3b56"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.i686-linux-gnu.tar.gz"
[[OptimPack]]
arch = "i686"
git-tree-sha1 = "5a3c9c0bbbbc6b24465cb5c9c0d5b62811d9c6e2"
libc = "musl"
os = "linux"

    [[OptimPack.download]]
    sha256 = "b273f55fa86eefd2d94aaec1c0bb3b43f1551a5315cf042bddb6af8aeb275998"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.i686-linux-musl.tar.gz"
[[OptimPack]]
arch = "i686"
git-tree-sha1 = "c4cafa70992d0e57f27510bb0590e8cc02085939"
os = "windows"

    [[OptimPack.download]]
    sha256 = "1fb66303075ac0d900e7d71b97a6d5f2dc8100bb67871571034630663166f33e"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.i686-w64-mingw32.tar.gz"
[[OptimPack]]
arch = "powerpc64le"
git-tree-sha1 = "e29e6a00ec6eec04714a900ea885f07d557fce21"
libc = "glibc"
os = "linux"

    [[OptimPack.download]]
    sha256 = "2f90875176950e0a722190961b12a90386f594a9afeabc5f7611c14733646663"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.powerpc64le-linux-gnu.tar.gz"
[[OptimPack]]
arch = "x86_64"
git-tree-sha1 = "04b7c148b18d4ebc7d4b9f496986cf2db380459e"
os = "macos"

    [[OptimPack.download]]
    sha256 = "9e05c95fbf2121cc27a975d2533c14b9accfbeeed3a0daa1ea96eb4bd377504d"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.x86_64-apple-darwin.tar.gz"
[[OptimPack]]
arch = "x86_64"
git-tree-sha1 = "970b77be69a75efb7f46397b4df542e9911b6a97"
libc = "glibc"
os = "linux"

    [[OptimPack.download]]
    sha256 = "7599f4fdae2d7452042fc705cc11245e67fcf07745360bdd81dfb02a6105ddcb"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.x86_64-linux-gnu.tar.gz"
[[OptimPack]]
arch = "x86_64"
git-tree-sha1 = "9d7521748dcc71e7b6c7a8e0eb2c48852be1cf6b"
libc = "musl"
os = "linux"

    [[OptimPack.download]]
    sha256 = "b36a1e3f91cf25b00e245bccbc2553e61b4ad306653742d8adb4d02fa9a8d5ba"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.x86_64-linux-musl.tar.gz"
[[OptimPack]]
arch = "x86_64"
git-tree-sha1 = "66db56ffef7d72a11f84a7f60f42bdf7b7b38ff8"
os = "freebsd"

    [[OptimPack.download]]
    sha256 = "05d9b6f2538a6df890240eeef36b428539da3abc27c70d11e04bfd9c13b6745d"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.x86_64-unknown-freebsd.tar.gz"
[[OptimPack]]
arch = "x86_64"
git-tree-sha1 = "cb4cd2ec7746509c7f83ba4cb321f5b55acc6097"
os = "windows"

    [[OptimPack.download]]
    sha256 = "91622d3051e5772d1caa07b986867f14376f4d490a26103577a16bd6f5b1c4c2"
    url = "https://github.com/JuliaBinaryWrappers/OptimPack_jll.jl/releases/download/OptimPack-v3.2.0+0/OptimPack.v3.2.0.x86_64-w64-mingw32.tar.gz"
