# Autogenerated wrapper script for OptimPack_jll for i686-w64-mingw32
export libbobyqa, libcobyla, libnewuoa, libopk

JLLWrappers.@generate_wrapper_header("OptimPack")
JLLWrappers.@declare_library_product(libbobyqa, "libbobyqa-2.dll")
JLLWrappers.@declare_library_product(libcobyla, "libcobyla-2.dll")
JLLWrappers.@declare_library_product(libnewuoa, "libnewuoa-2.dll")
JLLWrappers.@declare_library_product(libopk, "libopk-3.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbobyqa,
        "bin\\libbobyqa-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcobyla,
        "bin\\libcobyla-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnewuoa,
        "bin\\libnewuoa-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopk,
        "bin\\libopk-3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
